cargo-features = ["edition"]

[package]
name = "stp"
version = "0.1.0"
authors = ["Luiz Fonseca <eu@luiz.cc>"]
edition = "2018"

[dependencies]
rand = "0.5.4"
geo = "0.9.1"
csv = "1"
log = "0.4.3"
flexi_logger = "0.9"
serde = "1.0.70"
serde_derive = "1.0.70"
